### ISSUE TITLE
Incorportate assembled mt genome

### ISSUE THREAD

**Issue by Astahlke** [isugifNF/polishCLR#13]
Concat assembled MT contig `Pgos/RawData/MT_Contig/Pgos_mtDNA_contig.fasta` to primary assembly for polishing in arrow

**Comment by j23414** [comment]
Add a  `--mito_assembly` (`--mt_assembly`?) or concat the mitocondrial genome before running.

```
if (params.mito_assembly){
  mito_ch = channel.of(params.mito_assembly, checkIfExists:true)
  asm_ch = channel.fromPath(params.primary_assembly, checkIfExists:true) | combine(mito_ch) | addMito
} else {
   asm_ch = channel.fromPath(params.primary_assembly, checkIfExists:true)
}
```

This is just a reminder to myself to add, after current run completes
