### ISSUE TITLE
Flag renaming for clarity

### ISSUE THREAD

**Issue by Astahlke** [isugifNF/polishCLR#25]
I was confused about how to direct the pipeline to skip 02_Arrow if the Falcon assembly has already been polished. Currently you would supply --falcon-unzip True to skip  to purge_dups. I suggest that --falcon_unzip be changed to falcon_polish for clarity. 

I think there may be some other renaming, eg steptwo that could be more clear as well.

**Comment by j23414** [comment]
Yes, and `--step 1` and `--step 2`. I'll make these flag-y changes on the "edits_2021" branch. Want to run some tests before merging.
