### ISSUE TITLE
Atlas issues

### ISSUE THREAD

**Issue by Astahlke** [isugifNF/polishCLR#26]
Running on atlas brings up a bunch of issues. 

- Trying to generate histograms for purge_dups:

```
Traceback (most recent call last):
  File "/project/ag100pest/software/purge_dups/scripts/hist_plot.py", line 4, in <module>
    import matplotlib as mpl
```

- For BUSO, you can either kick to the process to `queue='service'` in `configs/atlas.config` or direct to an offline directory, eg

```
    --offline \
   --download_path /project/ag100pest/busco_datasets
```

**Comment by j23414** [comment]
Just a note that `hist_plot.py` is deprecated for our pipeline, but please let me know if I'm mistaken.

Good note on BUSCO, sounds like we can modify `busco_params` for Atlas.

```
--busco_params                 Parameters passed to busco [default: ' -l insecta_odb10 -m genome -f ']
```

Or something like: 

```
nextflow run isugifNF/polishCLR -r main \
   --busco_params " -l insecta_odb10 -m genome -f --offline --download_path /project/ag100pest/busco_datasets" \
   # rest of the arguments . . .
``` 

which gets dropped in here:

https://github.com/isugifNF/polishCLR/blob/d1a1b9f8b08132a6f5715f774c0ddb915983bdce/modules/busco.nf#L33-L37
