### ISSUE TITLE
add: smaller dataset

### ISSUE THREAD

**Issue by j23414** [isugifNF/polishCLR#38]
Either as a small genome, or one of several simulated genome options

Option 1: Near ideal case, no repeated sequences in whole genome
  ACGT AACCGGTT AAACCCGGGTTT... (avoid short reads mapping to multiple locations, near ideal case)
  
Option 2: Same as option 1, but introduce random errors

Option 3: Same as option 1, but introduce polyploidy

**Comment by j23414** [comment]
Went with `a small genome`. 

Adding some notes here from a debugging session.

Illumina and PacBio reads have been subsetted into three files which match to Hzea Chr 1, thanks Ben and Amanda.

| Param | Files |
|:--|:--|
|--illumina_reads |"testpolish_{R1,R2}.fq" |
| --pacbio_reads | "test.1.filtered.bam" |

These are passed to all three cases:

### Case 1

Should only require the addition of the assembly file (or Hzea Chr 1) and a mitochondrial file

```
 nextflow run isugifNF/polishCLR -r main \
  --primary_assembly "GCF_022581195.2_ilHelZeax1.1_chr1.fa" \. <== HERE
  --mitochondrial_assembly "GCF_022581195.2_ilHelZeax1.1_mito.fa" \ <== HERE
  --illumina_reads "testpolish_{R1,R2}.fq" \
  --pacbio_reads "test.1.filtered.bam" \
```

### Case 2

Should require Case 1 files, plus the alternate assembly file (chr 1) from Falcon unzip but not polished

```
 nextflow run isugifNF/polishCLR -r main \
  --primary_assembly "GCF_022581195.2_ilHelZeax1.1_chr1.fa" \. <== HERE
  --alternate_assembly "data/alternate.fasta" \ <== pull from Hzea from 3-unzip folder
  --mitochondrial_assembly "GCF_022581195.2_ilHelZeax1.1_mito.fa" \ <== HERE
  --illumina_reads "testpolish_{R1,R2}.fq" \
  --pacbio_reads "test.1.filtered.bam" \
```

### Case 3

Should require Case 1 files, plus the alternate assembly file (chr 1) from Falcon unzip polished

```
 nextflow run isugifNF/polishCLR -r main \
  --primary_assembly "GCF_022581195.2_ilHelZeax1.1_chr1.fa" \. <== HERE
  --alternate_assembly "data/alternate.fasta" \ <== pull from Hzea from 4-polish folder
  --mitochondrial_assembly "GCF_022581195.2_ilHelZeax1.1_mito.fa" \ <== HERE
  --illumina_reads "testpolish_{R1,R2}.fq" \
  --pacbio_reads "test.1.filtered.bam" \
```

### Trio dataset  (Optional but out of scope)

Did we want to consider providing a minimum paternal/maternal trio dataset?

**Comment by j23414** [comment]
Just saw, thanks!

* primary, alternative assemblies: https://data.nal.usda.gov/dataset/data-polishclr-example-input-genome-assemblies
* mitochondrial: https://www.ncbi.nlm.nih.gov/nuccore/NC_061507.1?report=fasta

**Comment by Astahlke** [comment]
Smaller test datasets have been added to https://data.nal.usda.gov/dataset/data-polishclr-example-input-genome-assemblies 

[ NOTE - Data files added 2022-11-01:
- Test long reads - test.1.filtered.bam_.gz
- Test short reads R1 - testpolish_R1.fastq
- Test short reads R2 - testpolish_R2.fastq
- Chromosome 30 of H. zea - GCF_022581195.2_ilHelZeax1.1_chr30.fasta ]
- 
@j23414, can you work these into the continuous integration workflow? I'll add them to the documentation!

**Comment by j23414** [comment]
On it, thank you!

**Comment by j23414** [comment]
Just an update that I'm running the CI tests in a [separate repo](https://github.com/j23414/ci_test) before merging. Want to check for data transfer/runtime limits.

**Comment by j23414** [comment]
I'll vetoing running the test data in CI, since 6hrs to download & run in github ci would delay testing and merging code.
> [Nextflow stub test](https://github.com/j23414/ci_test/actions/runs/3371892166/jobs/5594677515#logs)
> cancelled in 6h 0m 15s

Remaining tasks for this issue include adding test data instructions at the top of 

* [Case_01.md](https://github.com/isugifNF/polishCLR/blob/main/docs/Case_01.md)
* [Case_02.md](https://github.com/isugifNF/polishCLR/blob/main/docs/Case_02.md)
* [Case_03.md](https://github.com/isugifNF/polishCLR/blob/main/docs/Case_03.md)

**Comment by j23414** [comment]
https://github.com/isugifNF/polishCLR/pull/63

**Comment by j23414** [comment]
@Astahlke @Sivanandan can we close this issue?

**Comment by Sivanandan** [comment]
Yep! I think we can.
