### ISSUE TITLE
What's up with the java install?

### ISSUE THREAD

**Issue by Astahlke** [isugifNF/polishCLR#40]
I can bypass this error by loading the java module on ceres. 

```
/project/ag100pest/conda_envs/polishCLR/lib/jvm/bin/java: symbol lookup error: /project/ag100pest/conda_envs/polishCLR/lib/jvm/bin/java: undefined symbol: JLI_StringDup
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /project/ag100pest/conda_envs/polishCLR/lib/jvm/bin/java
 NXF_OPTS:
```
Does `envionment.yml` need a fix?

**Comment by Astahlke** [comment]
@j23414 and @isugif - still getting this error. Any ideas?

**Comment by j23414** [comment]
Haha, @Sivanandan and I were also running into that. Nextflow requires Java 11 or greater. We just added `openjdk=11` to:

* https://github.com/isugifNF/polishCLR/blob/d8bc637e7b82af6953c23f4770de4f87a4413d43/environment.yml#L25

But it's not merged yet. Waiting until new Docker image is published to DockerHub.

<del>
If you're on HPC, might be able to add it manually:

```
conda activate  /project/ag100pest/conda_envs/polishCLR
conda install openjdk=11

# Then find the openjdk java executable
find /project/ag100pest/conda_env/polishCLR/ | grep "java$"
JAVA_HOME=`find /project/ag100pest/conda_env/polishCLR/ | grep "java$"`

# Check if nextflow finds java and runs normally, or if you're still getting the error.
nextflow -version
```

</del>

Nevermind, you got it. Yes, it's being added to `environment.yml` 😄

**Comment by j23414** [comment]
Or if you can load a java 11 from HPC

```
module spyder java
```

Nextflow is looking for the path to the executable java `JAVA_HOME`

```
export JAVA_HOME=`which java`
```
