### ISSUE TITLE
Mitogenome missing error

### ISSUE THREAD

**Issue by Astahlke** [isugifNF/polishCLR#41]
It would be beneficial to get meaningful errors when the inputs are not provided but are required. For instance, the absence of the mitogenome when using a FALCON-unzipped assemblies causes the workflow to fail with no useful error message.

**Comment by Astahlke** [comment]
Is this resolved with https://github.com/isugifNF/polishCLR/pull/55? Can the pipeline run now without a mitogenome? Splits included?

**Comment by j23414** [comment]
> It would be beneficial to get meaningful errors when the inputs are not provided but are required

and 

> Is this resolved with https://github.com/isugifNF/polishCLR/pull/55?

Yes, it's resolved with #55 such as 

https://github.com/isugifNF/polishCLR/blob/b44d194006df1c6a5bc2e08f04c5fda8acaa4743/main.nf#L208-L216

**Comment by j23414** [comment]
> Can the pipeline run now without a mitogenome? Splits included?

Yes, splits was generalized so mitogenome is not required:

https://github.com/isugifNF/polishCLR/blob/b44d194006df1c6a5bc2e08f04c5fda8acaa4743/modules/helper_functions.nf#L62-L75
